version: '3.8'

# =============================================================================
# OPTIMIZED DOCKER COMPOSE - FOODSAVE AI
# Enhanced performance, security, and resource management
# =============================================================================

services:
  # =============================================================================
  # BACKEND - FASTAPI (Zoptymalizowany dla RTX 3060)
  # =============================================================================
  backend:
    build:
      context: ../..
      dockerfile: src/backend/Dockerfile.dev
    container_name: foodsave-backend
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite+aiosqlite:///data/foodsave.db
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
      - REDIS_USE_CACHE=True
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=SpeakLeash/bielik-11b-v2.3-instruct:Q5_K_M
      - OPENWEATHER_API_KEY=your_openweather_api_key_here
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=your-super-secret-key-for-development-only
      - CORS_ORIGINS=*
      - PORT=8000
      - HOST=0.0.0.0
      # GPU Configuration dla RTX 3060
      - USE_GPU_OCR=true
      - GPU_DEVICE_ID=0
      - GPU_MEMORY_LIMIT=10GB
      # Performance optimization dla 32GB RAM
      - OCR_TIMEOUT=600
      - ANALYSIS_TIMEOUT=480
      - MAX_FILE_SIZE=10485760
      # Enhanced concurrency dla RTX 3060
      - WORKERS_PER_CORE=2
      - MAX_WORKERS=8
      - WEB_CONCURRENCY=8
      - PYTHONUNBUFFERED=1
      # Gmail Inbox Zero Enhanced Configuration
      - GMAIL_INBOX_ZERO_ENABLED=true
      - GMAIL_CACHE_TTL_HOURS=24
      - GMAIL_RATE_LIMIT_PER_SECOND=10
      - GMAIL_BATCH_SIZE=100
      - GMAIL_PREFILTER_ENABLED=true
      - GMAIL_SMART_CACHE_SIZE=1000
      - GMAIL_EXPONENTIAL_BACKOFF_MAX_RETRIES=3
      - GMAIL_QUOTA_EXCEEDED_BACKOFF_MULTIPLIER=1.5
      - GMAIL_ADAPTIVE_RATE_LIMITING=true
      - GMAIL_SUCCESS_RATE_THRESHOLD=0.95
      - GMAIL_FAILURE_RATE_THRESHOLD=0.8
      - GMAIL_BATCH_PROCESSING_ENABLED=true
      - GMAIL_CONCURRENT_SEMAPHORE_LIMIT=5
      - GMAIL_PREFILTER_CONFIDENCE_THRESHOLD=0.8
      - GMAIL_ML_CLASSIFIER_ENABLED=true
      - GMAIL_NEWSLETTER_PATTERNS=newsletter,unsubscribe,mailing list,weekly digest,monthly update,email digest,roundup,summary
      - GMAIL_SPAM_KEYWORDS=viagra,casino,lottery,winner,congratulations,free money,urgent,act now,limited time,click here,unsubscribe,remove from list,earn money,work from home
      - GMAIL_WHITELIST_DOMAINS=linkedin.com,github.com,stackoverflow.com,amazon.com,google.com,microsoft.com,apple.com,netflix.com,spotify.com,dropbox.com,slack.com
      - GMAIL_SAFE_SENDERS=
      - GMAIL_AUTOMATED_PATTERNS=receipt,confirmation,order,booking,reservation,payment,invoice,statement,report,notification
      # Telegram Bot Configuration
      - TELEGRAM_BOT_TOKEN=7689926174:AAHIidXCkrH4swWEz0EW0md8A196HvFggP4
      - TELEGRAM_BOT_USERNAME=foodsave_ai_bot
      - TELEGRAM_BOT_NAME=FoodSave AI Assistant
      - TELEGRAM_WEBHOOK_SECRET=fixed_secret_token_for_telegram_webhook
      - TELEGRAM_MAX_MESSAGE_LENGTH=4096
      - TELEGRAM_RATE_LIMIT_PER_MINUTE=30
      # Gmail API Configuration
      - GMAIL_SCOPES=https://www.googleapis.com/auth/gmail.readonly,https://www.googleapis.com/auth/gmail.modify,https://www.googleapis.com/auth/gmail.labels
      - OAUTH_PORT=8002
      - GMAIL_CREDENTIALS_PATH=/app/config/gmail_auth.json
      - GMAIL_TOKEN_PATH=/app/config/gmail_token.json
    volumes:
      - backend_data:/app/data
      - backend_logs:/app/logs
      - temp_uploads:/app/temp_uploads
      # - ./config:/app/config
      # Mount source code for development hot-reload - disabled due to permission issues
      # - ./src:/app/src:ro
      # - ./main.py:/app/main.py:ro
    ports:
      - "8000:8000"
      - "8002:8002"
    networks:
      - foodsave-network
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 8G                   # Zwiększone z 6G dla 32GB RAM
          cpus: '4.0'                  # Zwiększone z 3.0
        reservations:
          memory: 4G                   # Zwiększone z 3G
          cpus: '2.0'                  # Zwiększone z 1.5
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # =============================================================================
  # CELERY WORKER - ASYNCHRONOUS TASK PROCESSING (Zoptymalizowany)
  # =============================================================================
  celery-worker:
    build:
      context: ../..
      dockerfile: Dockerfile.backend.optimized
      target: production
    container_name: foodsave-celery-worker
    restart: unless-stopped
    command: celery -A worker worker --loglevel=info --concurrency=4
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///data/foodsave.db
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
      - REDIS_USE_CACHE=True
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=SpeakLeash/bielik-11b-v2.3-instruct:Q5_K_M
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # Enhanced concurrency dla RTX 3060
      - CELERY_CONCURRENCY=4           # Zwiększone z 2
      - CELERY_MAX_TASKS_PER_CHILD=1000
      - CELERY_PREFETCH_MULTIPLIER=4
      # GPU Configuration dla Celery
      - USE_GPU_OCR=true
      - GPU_DEVICE_ID=0
      - GPU_MEMORY_LIMIT=10GB
      # Performance optimization
      - OCR_TIMEOUT=600
      - ANALYSIS_TIMEOUT=480
      - MAX_FILE_SIZE=10485760
      # Fix for Celery security warning
      - C_FORCE_ROOT=true
      # Gmail Inbox Zero Enhanced Configuration for Celery
      - GMAIL_INBOX_ZERO_ENABLED=true
      - GMAIL_CACHE_TTL_HOURS=24
      - GMAIL_RATE_LIMIT_PER_SECOND=5
      - GMAIL_BATCH_SIZE=50
      - GMAIL_PREFILTER_ENABLED=true
      - GMAIL_SMART_CACHE_SIZE=500
      - GMAIL_EXPONENTIAL_BACKOFF_MAX_RETRIES=3
      - GMAIL_QUOTA_EXCEEDED_BACKOFF_MULTIPLIER=1.5
      - GMAIL_ADAPTIVE_RATE_LIMITING=true
      - GMAIL_SUCCESS_RATE_THRESHOLD=0.95
      - GMAIL_FAILURE_RATE_THRESHOLD=0.8
      - GMAIL_BATCH_PROCESSING_ENABLED=true
      - GMAIL_CONCURRENT_SEMAPHORE_LIMIT=3
      - GMAIL_PREFILTER_CONFIDENCE_THRESHOLD=0.8
      - GMAIL_ML_CLASSIFIER_ENABLED=true
    volumes:
      - backend_data:/app/data
      - backend_logs:/app/logs
      - temp_uploads:/app/temp_uploads
    networks:
      - foodsave-network
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "celery", "-A", "worker", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 4G                   # Zwiększone z 2G
          cpus: '2.0'                  # Zwiększone z 1.0
        reservations:
          memory: 2G                   # Zwiększone z 1G
          cpus: '1.0'                  # Zwiększone z 0.5
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # =============================================================================
  # FRONTEND - NEXT.JS APPLICATION
  # =============================================================================
  frontend:
    build:
      context: ../../modern-frontend
      dockerfile: Dockerfile
      target: production
    container_name: foodsave-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
      # Performance optimizations
      - NEXT_SHARP_PATH=/app/node_modules/sharp
      - NEXT_OPTIMIZE_FONTS=true
      - NEXT_OPTIMIZE_IMAGES=true
      # Gmail Inbox Zero Frontend Configuration
      - NEXT_PUBLIC_GMAIL_INBOX_ZERO_ENABLED=true
      - NEXT_PUBLIC_GMAIL_BATCH_MODE_ENABLED=true
      - NEXT_PUBLIC_GMAIL_KEYBOARD_SHORTCUTS_ENABLED=true
      - NEXT_PUBLIC_GMAIL_GAMIFICATION_ENABLED=true
      - NEXT_PUBLIC_GMAIL_PROGRESS_TRACKING_ENABLED=true
      - NEXT_PUBLIC_GMAIL_RESPONSIVE_DESIGN_ENABLED=true
      - NEXT_PUBLIC_GMAIL_PERFORMANCE_METRICS_ENABLED=true
      - NEXT_PUBLIC_GMAIL_EXPERIENCE_POINTS_ENABLED=true
      - NEXT_PUBLIC_GMAIL_LEVEL_SYSTEM_ENABLED=true
      - NEXT_PUBLIC_GMAIL_BADGE_SYSTEM_ENABLED=true
      - NEXT_PUBLIC_GMAIL_STREAK_TRACKING_ENABLED=true
      - NEXT_PUBLIC_GMAIL_EFFICIENCY_TRACKING_ENABLED=true
    ports:
      - "8085:3000"
    networks:
      - foodsave-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    volumes:
      - frontend_cache:/app/.next/cache
      # Mount source code for development hot-reload
      - ../../modern-frontend/src:/app/src

  # =============================================================================
  # TELEGRAM POLLER - BOT POLLING SERVICE
  # =============================================================================
  telegram-poller:
    build:
      context: ../..
      dockerfile: Dockerfile.backend.optimized
      target: production
    container_name: foodsave-telegram-poller
    restart: unless-stopped
    command: python3 docker_telegram_poller.pyc
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
      - TELEGRAM_BOT_TOKEN=7689926174:AAHIidXCkrH4swWEz0EW0md8A196HvFggP4
    volumes:
      - telegram_logs:/app/logs
    networks:
      - foodsave-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # =============================================================================
  # REDIS - CACHE (Zoptymalizowany dla 32GB RAM)
  # =============================================================================
  redis:
    image: redis:7-alpine
    container_name: foodsave-redis
    restart: unless-stopped
    command: >
      redis-server 
      --appendonly yes 
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru 
      --save 900 1 
      --save 300 10 
      --save 60 10000
      --tcp-keepalive 300
      --timeout 0
      --tcp-backlog 511
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - foodsave-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 3G                   # Zwiększone z 512M
          cpus: '1.0'                  # Zwiększone z 0.25
        reservations:
          memory: 1G                   # Zwiększone z 256M
          cpus: '0.5'                  # Zwiększone z 0.1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # =============================================================================
  # OLLAMA - AI MODELS (Zoptymalizowany dla RTX 3060)
  # =============================================================================
  ollama:
    image: ollama/ollama:latest
    container_name: foodsave-ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=24h
      # GPU Configuration dla RTX 3060 (12GB VRAM)
      - OLLAMA_GPU_LAYERS=43          # Zwiększone z 35
      - OLLAMA_NUM_PARALLEL=4          # Zwiększone z 2
      - OLLAMA_MAX_LOADED_MODELS=3     # Zwiększone z 2
      - OLLAMA_FLASH_ATTENTION=1       # Włączone
      # Performance optimizations
      - OLLAMA_GPU_MEMORY_UTILIZATION=0.85
      - OLLAMA_BATCH_SIZE=512
      - OLLAMA_CONTEXT_SIZE=8192
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - foodsave-network
    healthcheck:
      test: ["CMD", "pgrep", "ollama"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 8G                   # Zwiększone z 4G
          cpus: '3.0'                  # Zwiększone z 2.0
        reservations:
          memory: 4G                   # Zwiększone z 2G
          cpus: '1.5'                  # Zwiększone z 1.0
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # =============================================================================
  # PERPLEXICA - AI-POWERED SEARCH
  # =============================================================================
  perplexica-searxng:
    image: docker.io/searxng/searxng:latest
    container_name: foodsave-perplexica-searxng
    restart: unless-stopped
    environment:
      - SEARXNG_SETTINGS_PATH=/usr/local/searxng/searx/settings.yml
      - SEARXNG_SECRET=foodsave-secret-key-12345
    ports:
      - "4000:8080"
    networks:
      - foodsave-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  perplexica-app:
    image: itzcrazykns1337/perplexica:main
    container_name: foodsave-perplexica-app
    restart: unless-stopped
    environment:
      - SEARXNG_API_URL=http://perplexica-searxng:8080
      - DATA_DIR=/home/perplexica
    ports:
      - "3000:3000"
    networks:
      - foodsave-network
    volumes:
      - perplexica_data:/home/perplexica/data
      - perplexica_uploads:/home/perplexica/uploads
      - ./perplexica-docker/config.toml:/home/perplexica/config.toml:ro
    depends_on:
      perplexica-searxng:
        condition: service_healthy
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

networks:
  foodsave-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  redis_data:
    driver: local
  ollama_data:
    driver: local
  frontend_cache:
    driver: local
  backend_data:
    driver: local
  backend_logs:
    driver: local
  temp_uploads:
    driver: local
  telegram_logs:
    driver: local
  perplexica_data:
    driver: local
  perplexica_uploads:
    driver: local